
-- in Terminal
-- create database:
-- createdb -U twill noteful

-- create tables:
-- npm run migrate

-- seed tables:
-- psql -U twill -d noteful -f ./seeds/seed.folder.sql
-- psql -U twill -d noteful -f ./seeds/seed.note.sql

-- create test database:
-- createdb -U twill noteful-test

-- create test tables:
-- npm run migrate:test

-- seed test tables:
-- psql -U twill -d noteful-test -f ./seeds/seed.folder.sql
-- psql -U twill -d noteful-test -f ./seeds/seed.note.sql


-- in psql:
-- postgres=> CREATE DATABASE noteful OWNER twill;
-- postgres=> \c noteful
-- noteful=> \i ~/path/to/file/seeds.sql

CREATE TABLE note (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  content TEXT NOT NULL,
  modified TIMESTAMP NOT NULL DEFAULT now()
);


