
CREATE TABLE folder (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL
);


ALTER TABLE note
  ADD COLUMN
  folderid INTEGER REFERENCES folder(id) ON DELETE CASCADE NOT NULL;


    -- to allow nulls in NOTE folderid if a folder with related notes is deleted:
    -- folderid INTEGER REFERENCES folder(id) ON DELETE SET NULL


    -- to Cascade Delete all related notes when a folder is deleted:
    -- folderid INTEGER REFERENCES folder(id) ON DELETE CASCADE NOT NULL,
