
CREATE TABLE folder (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL
);


ALTER TABLE note
  ADD COLUMN
  folderId INTEGER REFERENCES folder(id) ON DELETE CASCADE NOT NULL;


    -- to allow nulls in NOTE folderId if a folder with related notes is deleted:
    -- folderId INTEGER REFERENCES folder(id) ON DELETE SET NULL


    -- to Cascade Delete all related notes when a folder is deleted:
    -- folderId INTEGER REFERENCES folder(id) ON DELETE CASCADE NOT NULL,
